# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - master

# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'



# Trigger the pipeline when changes are pushed to 'main' branch
trigger:
- main

# Use the latest Ubuntu machine to run the pipeline
pool:
  vmImage: 'ubuntu-latest'

# Define pipeline stages
stages:

# Stage 1: Build
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    steps:
    - script: echo "Building the application..."
      displayName: 'Build Application'

# Stage 2: Test
- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build  # Runs only if Build succeeds
  jobs:
  - job: TestJob
    steps:
    - script: echo "Running tests..."
      displayName: 'Run Tests'

# Stage 3: Deploy
- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Test  # Runs only if Tests succeed
  condition: succeeded()  # Deploy only if previous stages pass
  jobs:
  - job: DeployJob
    steps:
    - script: echo "Deploying application..."
      displayName: 'Deploy Application'
